projectPrefix: pita
project: ${self:custom.projectPrefix}-pensieve
stage: ${opt:stage, 'development'}
region: us-east-1
subdomain: pensieve
host: pitam.io
s3FrontendBucket: ${self:custom.project}-${self:provider.stage}
