service: ${file(../config.yml):project}-backend

custom:
  projectPrefix: ${file(../config.yml):projectPrefix}
  project: ${file(../config.yml):project}

  serverless-offline:
    port: 5006

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${file(../config.yml):stage}
  region: ${file(../config.yml):region}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  startSession:
    handler: src/startSession/startSession.handler
    description: Start the session, receives otp, returns jwt
    memorySize: 128
    timeout: 3
    events:
      - http:
          method: post
          path: startSession
          cors: true # TODO: security should probably be more tight

